name: medea_flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Desktop/Web, based on GoogleWebRTC.
version: 0.8.0-dev
homepage: https://github.com/instrumentisto/flutter-webrtc
environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: 1.39.0  # should be the same as in `Cargo.lock`
  freezed_annotation: ^2.0.3
dev_dependencies:
  build_runner: ^2.2.0
  ffigen: 6.0.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.5
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.instrumentisto.medea_flutter_webrtc
        pluginClass: MedeaFlutterWebrtcPlugin
      ios:
        pluginClass: MedeaFlutterWebrtcPlugin
      linux:
        pluginClass: MedeaFlutterWebrtcPlugin
      macos:
        pluginClass: MedeaFlutterWebrtcPlugin
      windows:
        pluginClass: MedeaFlutterWebrtcPluginCApi
