name: medea_flutter_webrtc
description: Flutter WebRTC plugin for iOS/Android/Desktop/Web, based on GoogleWebRTC.
version: 0.8.0-dev
homepage: https://github.com/instrumentisto/flutter-webrtc
environment:
  flutter: ">=3.7.0"
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  collection: ^1.17.0
  ffi: ^2.0.1
  js: ^0.6.5
  flutter:
    sdk: flutter
  flutter_rust_bridge: 1.64.0  # should be the same as in `Cargo.lock`
  freezed_annotation: ^2.2.0
dev_dependencies:
  build_runner: ^2.3.2
  ffigen: 7.2.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  import_sorter: ^4.6.0

flutter:
  plugin:
    platforms:
      android:
        package: com.instrumentisto.medea_flutter_webrtc
        pluginClass: MedeaFlutterWebrtcPlugin
      ios:
        pluginClass: MedeaFlutterWebrtcPlugin
      linux:
        pluginClass: MedeaFlutterWebrtcPlugin
      macos:
        pluginClass: MedeaFlutterWebrtcPlugin
      windows:
        pluginClass: MedeaFlutterWebrtcPluginCApi
