[package]
name = "jason_flutter_webrtc"
version = "0.0.1"
edition = "2018"
build = "build.rs"

[lib]
name = "jason_flutter_webrtc"
crate-type = ["cdylib"]

[dependencies]
libwebrtc-sys = { path="../libwebrtc-sys" }

[build-dependencies]
cbindgen = "0.20"
