[package]
name = "mylibwebrtc" # jason-flutter-webrtc
version = "0.0.1"
edition = "2018"
build = "build.rs"

[lib]
name = "mylibwebrtc"
crate-type = ["cdylib"]

[dependencies]
libwebrtc-sys = { path="../libwebrtc-sys" }

[build-dependencies]
cbindgen = "0.20"
