[package]
name = "flutter-webrtc-native"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
libwebrtc-sys = { path = "../libwebrtc-sys" }
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
