[package]
name = "flutter-webrtc-native"
version = "0.0.1"
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
libwebrtc-sys = { path="../libwebrtc-sys" }

[build-dependencies]
cbindgen = "0.20"
