[package]
name = "libwebrtc-sys"
version = "0.0.0"
edition = "2021"
publish = false
links = "webrtc"

[dependencies]
cxx = "1.0"

[build-dependencies]
anyhow = "1.0"
cxx-build = "1.0"
dotenv = "0.15"
reqwest = { version = "0.11", features = ["blocking"] }
