name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: 2.10
  FLUTTER_CHANNEL: stable

jobs:

  ##########################
  # Linting and formatting #
  ##########################

  dartanalyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: flutter pub get

      - run: flutter analyze

  dartfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - run: flutter format lib/ test/ --set-exit-if-changed

      - run: flutter pub get

      - run: flutter pub run import_sorter:main --no-comments --exit-if-changed

  ktfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
            distribution: 'temurin'
            java-version: '17'

      - run: wget https://search.maven.org/remotecontent?filepath=com/facebook/ktfmt/0.33/ktfmt-0.33-jar-with-dependencies.jar
      - run: java -jar ktfmt-0.33-jar-with-dependencies.jar --set-exit-if-changed android/src/main/kotlin/
