name: CI

on:
  push:

env:
  RUST_BACKTRACE: 1

jobs:

  clippy:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - run: make cargo.lint

  rustfmt:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - run: make cargo.fmt check=yes

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    # TODO: Switch to `windows-latest` when stable Flutter stable will support
    #       MSVC 2022:
    #       https://github.com/flutter/flutter/issues/85922
    #       https://github.com/flutter/flutter/issues/96138
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.8.1
      - run: flutter config --enable-windows-desktop

      - run: make cargo.build
      - run: make flutter.build

      - name: Caching
        uses: action/cache@2
        key: testing
        with:
          path: windows/rust

  rustdoc:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: make cargo.doc

  test:
    needs: ['build']
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Cache
        uses: action/cache@2
        key: testing
        with:
          path: windows/rust
      - run: make cargo.test
      - run: make cargo.build
      - run: make flutter.test device=windows
