name: CI
# TODO(alexlapa): add dartfmt and dartanalyze
on:
  push:
    branches: ["windows-rework"]
  pull_request:
    branches: ["windows-rework"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VER: 2.8.1
  RUST_BACKTRACE: 1

jobs:

  ##########################
  # Linting and formatting #
  ##########################

  clippy:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - run: make cargo.lint

  rustfmt:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - run: make cargo.fmt check=yes




  ############
  # Building #
  ############

  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    # TODO: Switch to `windows-latest` when stable Flutter stable will support
    #       MSVC 2022:
    #       https://github.com/flutter/flutter/issues/85922
    #       https://github.com/flutter/flutter/issues/96138
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VER }}
      - run: flutter config --enable-windows-desktop

      - run: make cargo.build
      - run: make flutter.build

      - uses: actions/upload-artifact@v2
        with:
          name: build-rust
          path: windows/rust/
          retention-days: 1




  ###########
  # Testing #
  ###########

  test-rust:
    name: Test Rust crates
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - run: make cargo.test

  test-flutter:
    name: Test Flutter integration
    needs: ["build"]
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VER }}
      - run: flutter config --enable-windows-desktop

      - uses: actions/download-artifact@v2
        with:
          name: build-rust
          path: windows/rust/

      - run: make flutter.test device=windows




  #################
  # Documentation #
  #################

  rustdoc:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - run: make cargo.doc
