# name: CI

# on:
#   push:

# env:
#   RUST_BACKTRACE: 1

# jobs:
#   chocotest:
#     name: Chokotest
#     runs-on: windows-latest
#     steps:
#       - run: choco install make
#       - uses: actions/checkout@v2
#       - uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#       - 
