name: CI

on:
  issue_comment:
    types: ["created", "edited"]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  KTFMT_VER: 0.33
  RUST_BACKTRACE: 1

jobs:

  ################
  # Pull Request #
  ################

  inspect:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event) }}'
