name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FLUTTER_VERSION: '2.2.3'
  FLUTTER_CHANNEL: 'stable'

jobs:
  test:
    name: Flutter unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter packages get
      - run: flutter test

  check-dart-imports-order:
    name: Dart imports order
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter pub run import_sorter:main --no-comments --exit-if-changed

  dartfmt:
    name: Dart files formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter format lib/ test/ --set-exit-if-changed

  dartanalyze:
    name: Dart lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter analyze

  android-formatting:
    name: Formatting of Android Java files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"
          files: "android/src/main/java/com/cloudwebrtc/webrtc/**/*.java"
          version: 1.13.0
