name: Test

on:
  push:

jobs:
  test:
    name: Rust tests
    runs-on: windows-latest
    steps:
      - run: choco install make
      - run: make lib.download
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cd libwebrtc-sys && cargo test --test integration_test
  
